export const DEFAULT_BOT_CONFIG = [
  {
    id: "mm-core-a",
    name: "MM Core Alpha",
    botType: "MM-Core",
    symbolUniverse: ["INDEX"],
    latencyMs: { mean: 18, jitter: 8 },
    inventory: { maxAbs: 800, skewPerUnitTick: 0.002 },
    quote: {
      targetSpreadBp: 4,
      minEdgeTicks: 1,
      size: { mean: 6, sigma: 2 },
      iceberg: { enabled: true, display: 2, parent: 18 },
    },
    volAwareness: { widenFactorPerATR: 0.6, pauseAtATR: 2.5 },
    newsSensitivity: { beta: 0.7, halfLifeSec: 120 },
    risk: { maxLoss: 6000, maxDrawdown: 3200, killSwitch: true },
  },
  {
    id: "mm-core-b",
    name: "MM Core Beta",
    botType: "MM-Core",
    symbolUniverse: ["INDEX"],
    latencyMs: { mean: 26, jitter: 10 },
    inventory: { maxAbs: 700, skewPerUnitTick: 0.0015 },
    quote: {
      targetSpreadBp: 6,
      minEdgeTicks: 1,
      size: { mean: 5, sigma: 1.6 },
      iceberg: { enabled: false },
    },
    volAwareness: { widenFactorPerATR: 0.8, pauseAtATR: 3 },
    newsSensitivity: { beta: 0.5, halfLifeSec: 150 },
    risk: { maxLoss: 5200, maxDrawdown: 2800, killSwitch: true },
  },
  {
    id: "mm-hft-1",
    name: "HFT Quoter",
    botType: "MM-HFT",
    symbolUniverse: ["INDEX"],
    latencyMs: { mean: 6, jitter: 3 },
    inventory: { maxAbs: 140, skewPerUnitTick: 0.0008 },
    quote: { targetSpreadBp: 2, minEdgeTicks: 1, size: { mean: 2.4, sigma: 0.8 } },
    risk: { maxLoss: 1800, killSwitch: true },
  },
  {
    id: "mm-ice-1",
    name: "Iceberg Desk",
    botType: "MM-Iceberg",
    symbolUniverse: ["INDEX"],
    latencyMs: { mean: 45, jitter: 12 },
    quote: {
      size: { mean: 12, sigma: 3 },
      iceberg: { enabled: true, display: 3, parent: 40 },
    },
    inventory: { maxAbs: 1000, skewPerUnitTick: 0.001 },
    risk: { maxLoss: 7000, killSwitch: true },
  },
  {
    id: "exec-twap-1",
    name: "TWAP Executor",
    botType: "Exec-TWAP",
    parentOrder: { side: "buy", quantity: 2800, deadlineSec: 1800 },
    participationCapPct: 0.18,
    child: { meanQty: 18, randomize: true },
    latencyMs: { mean: 40, jitter: 15 },
    risk: { maxSlippageTicks: 6 },
  },
  {
    id: "exec-desk-1",
    name: "Desk Unwind",
    botType: "Exec-Desk",
    startInventory: 1800,
    latencyMs: { mean: 55, jitter: 18 },
    risk: { maxLoss: 9000, killSwitch: true },
  },
  {
    id: "exec-pov-1",
    name: "POV Algo",
    botType: "Exec-POV",
    parentOrder: { side: "sell", quantity: 3200 },
    participationCapPct: 0.22,
    latencyMs: { mean: 32, jitter: 14 },
    aggression: { base: "passive" },
    risk: { maxSlippageTicks: 5 },
  },
  {
    id: "dir-cta-1",
    name: "CTA Trend",
    botType: "Dir-CTA",
    fastWindow: 18,
    slowWindow: 90,
    threshold: 0.0009,
    latencyMs: { mean: 80, jitter: 25 },
    inventory: { maxAbs: 420 },
    risk: { maxLoss: 4800 },
  },
  {
    id: "dir-mr-1",
    name: "Stat Arb",
    botType: "Dir-MR",
    window: 80,
    zScoreEntry: 1.8,
    latencyMs: { mean: 75, jitter: 30 },
    inventory: { maxAbs: 350 },
    risk: { maxLoss: 4200 },
  },
  {
    id: "dir-news-1",
    name: "News Fund",
    botType: "Dir-News",
    newsSensitivity: { beta: 0.8, halfLifeSec: 150 },
    latencyMs: { mean: 60, jitter: 20 },
    inventory: { maxAbs: 360 },
    risk: { maxLoss: 5000 },
  },
  {
    id: "dir-rebal-1",
    name: "Rebalancer",
    botType: "Dir-Rebal",
    targetPosition: 0,
    periodSec: 900,
    latencyMs: { mean: 95, jitter: 40 },
    inventory: { maxAbs: 260 },
  },
  {
    id: "rv-pairs-1",
    name: "Pairs Arb",
    botType: "RV-Pairs",
    zScoreEntry: 2.2,
    zScoreExit: 0.6,
    latencyMs: { mean: 28, jitter: 9 },
    risk: { maxLoss: 4200, killSwitch: true },
  },
  {
    id: "rv-basis-1",
    name: "Basis Arb",
    botType: "RV-Basis",
    threshold: 1.5,
    latencyMs: { mean: 34, jitter: 12 },
    risk: { maxLoss: 3800, killSwitch: true },
  },
  {
    id: "noisy-1",
    name: "Retail Flow",
    botType: "Noisy",
    latencyMs: { mean: 140, jitter: 60 },
    inventory: { maxAbs: 60 },
  },
  {
    id: "spoof-educ",
    name: "Spoof Demo",
    botType: "Edu-Spoof",
    features: { enabled: false },
    latencyMs: { mean: 20, jitter: 6 },
  },
];

export function loadDefaultBotConfigs() {
  return DEFAULT_BOT_CONFIG.map((cfg) => ({ ...cfg, id: cfg.id }));
}

