export const DEFAULT_ENGINE_CONFIG = {
  tickMs: 250,
  leaderboardInterval: 2,
  fairSmooth: 0.12,
  fairMaxStepPct: 0.01,
  priceAcceleration: 0.02,
  priceDamping: 0.15,
  velocityCapPct: 0.004,
  noisePct: 0.0015,
  turbulenceNoisePct: 0.001,
  maxPosition: 5,
  startPrice: 100,
  defaultPriceMode: "orderflow",
  newsImpulseFactor: 0.35,
  newsImpulseDecay: 0.88,
  newsImpulseCap: 18,
  orderFlowImpact: 0.65,
  orderFlowDecay: 0.55,
  orderFlowFairPull: 0.015,
  depthImbalanceImpact: 0.4,
  depthImbalanceImpactCap: 8,
  sweepImpactFactor: 0.6,
  sweepImpactDecay: 0.65,
  sweepImpactCap: 12,
  thinBookBoost: 1.2,
  thinBookBoostCap: 3,
  sweepRegenDampen: 0.55,
  tradeLotSize: 1,
  flowMix: { market: 0.6, limit: 0.4 },
  ambientFlow: {
    enabled: false,
    minIntervalMs: 320,
    maxIntervalMs: 1400,
    idleThresholdMs: 900,
    minQty: 0.6,
    meanQty: 3,
    sigmaQty: 1.4,
    maxLevelsAway: 4,
    anchorToFair: true,
  },
  orderBook: {},
};

export const DEFAULT_PRODUCT = {
  name: "Demo Asset",
  startPrice: 100,
};
